image: rust:1.44.0

test:
  script:
    - infra/ci/ci.sh test
  cache:
    paths:
      - target/

junit:
  script:
    - cargo install cargo-junit
    - infra/ci/ci.sh junit
  cache:
    paths:
      - target/
  artifacts:
    reports:
      junit: target/JUnit.xml

coverage:
  script:
    - cargo install cargo-tarpaulin -f
    - infra/ci/ci.sh coverage
  cache:
    paths:
      - target/

build-linux:
  script:
    - infra/ci/ci.sh build_linux
  cache:
    paths:
      - target/
  artifacts:
    paths:
      - target/release/tt

build-windows:
  script:
    - uname -a
    - apt-get update
    - apt-get -y install mingw-w64
    - rustup toolchain install stable-x86_64-pc-windows-gnu
    - rustup target add x86_64-pc-windows-gnu
    - infra/ci/ci.sh build_windows
    - ls target
  cache:
    paths:
      - target/

format:
  script:
    - rustup component add rustfmt
    - infra/ci/ci.sh fmt
  cache:
    paths:
      - target/

clippy:
  script:
    - rustup component add clippy
    - infra/ci/ci.sh clippy
  cache:
    paths:
      - target/
