# tool-tool configuration file - cf. https://gitlab.com/manuelwoelker/tool-tool/-/blob/master/README.md
tools:
  - name: lsd
    version: 0.17.0
    download:
      linux: https://github.com/Peltoche/lsd/releases/download/${version}/lsd-${version}-x86_64-unknown-linux-gnu.tar.gz
      windows: https://github.com/Peltoche/lsd/releases/download/${version}/lsd-${version}-x86_64-pc-windows-msvc.zip

  - name: openjdk
    version: 8u252-b09.1
    download:
      linux: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${version}/OpenJDK8U-jdk_x86-32_windows_hotspot_8u252b09.zip
      windows: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${version}/OpenJDK8U-jdk_x86-32_windows_hotspot_8u252b09.zip
    commands:
      java: bin/java

  - name: maven
    version: 3.6.3
    download:
      default: https://downloads.apache.org/maven/maven-3/${version}/binaries/apache-maven-${version}-bin.tar.gz
    commands:
      mvn: bin/mvn
    env:
      JAVA_HOME: ${dir:openjdk}

  - name: gradle
    version: 6.4.1
    download:
      default: https://downloads.gradle-dn.com/distributions/gradle-${version}-bin.zip
    commands:
      gradle: bin/gradle
    env:
      JAVA_HOME: ${dir:openjdk}

  - name: Node.js
    version: 12.17.0
    download:
      linux: https://nodejs.org/dist/v${version}/node-v${version}-win-x64.zip
      windows: https://nodejs.org/dist/v${version}/node-v${version}-win-x64.zip
    commands:
      node: node
      npm: npm
      npx: npx

  - name: Yarn
    version: 1.22.4
    download:
      default: https://github.com/yarnpkg/yarn/releases/download/v${version}/yarn-v${version}.tar.gz
    commands:
      yarn: ${cmd:node} ${dir}/bin/yarn.js

  - name: nethack
    version: 3.6.6
    strip_directories: 0
    download:
      windows: https://www.nethack.org/download/${version}/nethack-366-win-x86.zip
      linux: https://www.nethack.org/download/${version}/nethack-366-src.tgz
    commands:
      nethack: NetHackW

  - name: gitui
    version: 0.5.0
    strip_directories: 0
    download:
      windows: https://github.com/extrawurst/gitui/releases/download/v${version}/gitui-win.tar.gz
      linux: https://github.com/extrawurst/gitui/releases/download/v${version}/gitui-linux-musl.tar.gz

  - name: bazel
    version: 3.2.0
    strip_directories: 0
    download:
      windows: https://github.com/bazelbuild/bazel/releases/download/${version}/bazel-${version}-windows-x86_64.zip
      linux: https://github.com/bazelbuild/bazel/releases/download/${version}/bazel-${version}-linux-x86_64

  - name: Rust
    version: 1.44.0
    download:
      windows: https://static.rust-lang.org/dist/rust-${version}-x86_64-pc-windows-gnu.tar.gz
      linux: https://static.rust-lang.org/dist/rust-${version}-x86_64-unknown-linux-gnu.tar.gz
    commands:
      rustc: rustc/bin/rustc
      cargo: cargo/bin/cargo

  - name: Go
    version: 1.14.4
    download:
      windows: https://dl.google.com/go/go${version}.windows-amd64.zip
      linux: https://dl.google.com/go/go${version}.linux-amd64.tar.gz
    commands:
      go: bin/go
      gofmt: bin/gofmt

  - name: Python
    version: 3.8.3
    strip_directories: 0
    download:
      windows: https://www.python.org/ftp/python/${version}/python-${version}-embed-amd64.zip
      # No "plain" linux binaries available it seems
      linux: https://www.python.org/ftp/python/${version}/python-${version}-embed-amd64.zip
    commands:
      python: python

  - name: just
    version: 0.5.11
    strip_directories: 0
    download:
      windows: https://github.com/casey/just/releases/download/v${version}/just-v${version}-x86_64-pc-windows-msvc.zip
      linux: https://github.com/casey/just/releases/download/v${version}/just-v${version}-x86_64-unknown-linux-musl.tar.gz

  - name: TypeScript
    version: 3.9.5
    download:
      default: https://github.com/microsoft/TypeScript/releases/download/v${version}/typescript-${version}.tgz
    commands:
      tsc: ${cmd:node} ${dir}/bin/tsc

  - name: CMake
    version: 3.17.3
    download:
      windows: https://github.com/Kitware/CMake/releases/download/v${version}/cmake-${version}-win64-x64.zip
      linux: https://github.com/Kitware/CMake/releases/download/v${version}/cmake-${version}-Linux-x86_64.tar.gz
    commands:
      cmake: bin/cmake

  - name: pandoc
    version: 2.9.2.1
    download:
      windows: https://github.com/jgm/pandoc/releases/download/${version}/pandoc-${version}-windows-x86_64.zip
      linux: https://github.com/jgm/pandoc/releases/download/${version}/pandoc-${version}-linux-amd64.tar.gz

  - name: mdbook
    version: 0.3.7
    strip_directories: 0
    download:
      windows: https://github.com/rust-lang/mdBook/releases/download/v${version}/mdbook-v${version}-x86_64-pc-windows-msvc.zip
      linux: https://github.com/rust-lang/mdBook/releases/download/v${version}/mdbook-v${version}-x86_64-unknown-linux-gnu.tar.gz
