tools:
  - name: lsd
    version: 0.17.0
    download:
      linux: https://github.com/Peltoche/lsd/releases/download/${version}/lsd-${version}-x86_64-unknown-linux-gnu.tar.gz
      windows: https://github.com/Peltoche/lsd/releases/download/${version}/lsd-${version}-x86_64-pc-windows-msvc.zip

  - name: openjdk
    version: 8u252-b09.1
    download:
      linux: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${version}/OpenJDK8U-jdk_x86-32_windows_hotspot_8u252b09.zip
      windows: https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk${version}/OpenJDK8U-jdk_x86-32_windows_hotspot_8u252b09.zip
    commands:
      java: bin/java

  - name: maven
    version: 3.6.3
    download:
      default: https://downloads.apache.org/maven/maven-3/${version}/binaries/apache-maven-${version}-bin.tar.gz
    commands:
      mvn: bin/mvn
    env:
      JAVA_HOME: ${dir:openjdk}

  - name: gradle
    version: 6.4.1
    download:
      default: https://downloads.gradle-dn.com/distributions/gradle-${version}-bin.zip
    commands:
      gradle: bin/gradle
    env:
      JAVA_HOME: ${dir:openjdk}

  - name: Node.js
    version: 12.17.0
    download:
      linux: https://nodejs.org/dist/v${version}/node-v${version}-win-x64.zip
      windows: https://nodejs.org/dist/v${version}/node-v${version}-win-x64.zip
    commands:
      node: node
      npm: npm
      npx: npx

  - name: Yarn
    version: 1.22.4
    download:
      default: https://github.com/yarnpkg/yarn/releases/download/v${version}/yarn-v${version}.tar.gz
    commands:
      yarn: ${cmd:node} ${dir}/bin/yarn.js

  - name: nethack
    version: 3.6.6
    strip_directories: 0
    download:
      windows: https://www.nethack.org/download/${version}/nethack-366-win-x86.zip
    commands:
      nethack: NetHackW

  - name: gitui
    version: 0.5.0
    strip_directories: 0
    download:
      windows: https://github.com/extrawurst/gitui/releases/download/v${version}/gitui-win.tar.gz